version: '3.8'

services:
  deepguard-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepguard-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./weights:/app/weights
    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=3
    restart: unless-stopped
